add changes
faisalaltell/azure-rest-api-specs pull request #1
Opened 2023-01-24 16:00 UTC by faisalaltell12

# Choose a PR Template

Switch to "Preview" on this description then select one of the choices below.

<a href="?expand=1&template=data_plane_template.md">Click here</a> to open a PR for a Data Plane API.

<a href="?expand=1&template=control_plane_template.md">Click here</a> to open a PR for a Control Plane (ARM) API.

2023-01-24 16:13 UTC, kevinmichaelbowersox approved these changes

2023-01-24 19:59 UTC, anniruddh reviewed
Few minor fixes required, will need to backport to Share repo as well.

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_AdlsGen2AccountGet.json
> +        "id": "35E28F0E-DEA4-472F-84E4-5F1E45FB9937",
Good to match with id on line 5.

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_Activate_TenantEmailRegistration.json
> +    "repeatability-request-id": "b470712a-ffbc-4d9f-ab99-6640db8bbcb8",
Should this be part of request header?

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_Get.json
> +        "id": "35E28F0E-DEA4-472F-84E4-5F1E45FB9937",
Match with receivedShareId on line 5.

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_GetAll_AttachedReceivedShares.json
> +    }
Consider showing a nextLink as well in example.

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_Register_TenantEmailRegistration.json
> +    "repeatability-request-id": "b470712a-ffbc-4d9f-ab99-6640db8bbcb8"
In request header instead?

2023-01-24 19:59 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/SentShares_GetAll_SentShareInvitations.json
> +        "nextLink": "https://accountName.purview.azure.com/share/sentShareInvitations?api-version=2022-06-30-preview&skipToken=skip_token_to_fetch_more_sent_share_invitations"
sentShareId segment missing

2023-01-24 20:57 UTC, NateB2 requested changes

2023-01-24 20:57 UTC, NateB2 commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/examples/ReceivedShares_AdlsGen2AccountUpdate.json
> +        "Operation-Id": "25c78f97-0b0a-4fe9-ad39-883a482265cd"
The guid in the Operation-ID field should match the guid in the Azure-AsyncOperation and the Operation-Location field.

2023-01-24 21:13 UTC, anniruddh approved these changes

2023-01-24 21:23 UTC, faisalaltell commented
For any other changes, feel free to create a PR into this branch.

2023-01-24 22:10 UTC, NateB2 approved these changes

2023-01-24 22:18 UTC, merged

2023-01-25 18:04 UTC, anniruddh reviewed
Please remove /v2 from all routes in spec.

2023-01-25 18:04 UTC, anniruddh commented on specification/purview/data-plane/Azure.Analytics.Purview.Share/preview/2022-06-30-preview/share.json
> +    "/v2/receivedShares/{receivedShareId}": {
Need to remove /v2